services: 
    db:
        image: mysql:latest
        restart: always
        environment: 
            MYSQL_DATABASE: mydb
            MYSQL_ROOT_PASSWORD: 123456
        ports: 
            - "3307:3306"

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: 123456
        ports:
            - "8080:80"

    django-web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
